get_facts:
    cisco_ios_ssh:
        config_register: '0xF'
    fqdn: N/A
    hostname: SW3560-PORTO
    interfaces:
    - Vlan1
    - Vlan3
    - Vlan56
    - Vlan99
    - Vlan106
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    model: WS-C3560-24PS
    os_version: 12.2(55)SE6
    serial_number: FDO1137X1YL
    uptime: 85560
    uptime_string: 00:23:46:00
    vendor: cisco
    vlans:
    - '1'
    - '3'
    - '56'
    - '99'
    - '106'
    - '1002'
    - '1003'
    - '1004'
    - '1005'
changed: false
failed: false
