---
- name: GET FACTS
  connection: local
  hosts: cacuaco-rt
  gather_facts: no



  tasks:
    - ntc_get_facts:
	   platform: "cisco_ios_ssh"
	   host: "{{ inventory_hostname }}"
	   username: "{{ ansible_user }}"
	   password: "{{ ansible_ssh_pass }}"
      register: result




    - name: DISPLAY 
      debug:
         var: "{{ result }}" 
