---
- name: LOAD VARIABLE
  connection: local
  hosts: all
  gather_facts: no

  
  
  

  tasks:
    - include_vars: 
         dir : "host_vars/{{ inventory_hostname }}/{{ dir_facts }}"
         name: loading_vars


    - set_fact: getfact={{ loading_vars }}



#    - debug: var=getfact
